const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const html = fs.readFileSync(path.join(__dirname, '..', 'TRPG 작업 관리 도구.html'), 'utf8');
const first = { name: 'A', ammo: '6' }, second = { name: 'B', ammo: '10' };
const sheet = { id: 's', templateKey: 'coc7e', data: { weapons: [first, second] } };
let saves = 0, renders = 0;
const context = vm.createContext({ state: { characters: [{ id: 'c', sheets: [sheet] }] }, persist() { saves++; }, renderCharacterSheet() { renders++; } });
vm.runInContext(html.match(/function moveCocWeaponRow\([^]*?\n\}/)[0], context);
context.moveCocWeaponRow('c', 's', 0, 1);
assert.deepEqual(sheet.data.weapons, [second, first]);
context.moveCocWeaponRow('c', 's', 1, -1);
assert.deepEqual(sheet.data.weapons, [first, second]);
context.moveCocWeaponRow('c', 's', 0, -1);
context.moveCocWeaponRow('c', 's', 1, 1);
context.moveCocWeaponRow('c', 's', 0, 2);
assert.equal(saves, 2);
assert.equal(renders, 2);
vm.runInContext(html.match(/function toggleCocWeaponDetail\([^]*?\n\}/)[0], context);
const detail = { hidden: true };
const toggle = { closest: () => ({ nextElementSibling: detail }), setAttribute(key, value) { this[key] = value; } };
context.toggleCocWeaponDetail(toggle);
assert.equal(detail.hidden, false);
assert.equal(toggle['aria-expanded'], 'true');
context.toggleCocWeaponDetail(toggle);
assert.equal(detail.hidden, true);
let options, saved;
context.tbShowCtxMenu = (_x, _y, items) => { options = items; };
context.document = { querySelector: () => ({ style: {}, setAttribute() {}, querySelectorAll: () => [] }) };
context.saveSheetRepeatCell = (...args) => { saved = args; };
vm.runInContext(html.match(/function openCocWeaponDbMenu\([^]*?\n\}/)[0], context);
const button = { getBoundingClientRect: () => ({ left: 0, bottom: 20, width: 64 }), focus() {} };
context.openCocWeaponDbMenu({ stopPropagation() {}, currentTarget: button }, 'c', 's', 0);
options[2].action();
assert.equal(button.textContent, '+½DB');
assert.deepEqual(saved, ['c', 's', 'weapons', 0, 'db', '+½db']);
