const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const html = fs.readFileSync(path.join(__dirname, '..', 'TRPG 작업 관리 도구.html'), 'utf8');
const rows = ['A', 'B', 'C', 'D'].map(name => ({ name, era: name + '-era' }));
const sheet = { id: 's', templateKey: 'coc7e', data: { weapons: rows.slice() } };
let saves = 0, renders = 0;
const context = vm.createContext({ state: { characters: [{ id: 'c', sheets: [sheet] }] }, persist() { saves++; }, renderCharacterSheet() { renders++; } });
vm.runInContext(html.match(/function moveCocWeaponRow\([^]*?\n\}/)[0], context);
const order = () => sheet.data.weapons.map(row => row.name).join('');
context.moveCocWeaponRow('c', 's', 0, 4);
assert.equal(order(), 'BCDA');
context.moveCocWeaponRow('c', 's', 3, 0);
assert.equal(order(), 'ABCD');
context.moveCocWeaponRow('c', 's', 0, 2);
assert.equal(order(), 'BACD');
context.moveCocWeaponRow('c', 's', 2, 1);
assert.equal(order(), 'BCAD');
assert.deepEqual(sheet.data.weapons.map(row => row.era), ['B-era', 'C-era', 'A-era', 'D-era']);
const before = [saves, renders];
[[1, 1], [1, 2], [-1, 0], [4, 0], [0, 5], [0, -1], [0.5, 1], ['1', 2]].forEach(([from, to]) => context.moveCocWeaponRow('c', 's', from, to));
assert.deepEqual([saves, renders], before);
sheet.templateKey = 'insane';
context.moveCocWeaponRow('c', 's', 0, 2);
assert.deepEqual([saves, renders], before);
sheet.templateKey = 'coc7e';
vm.runInContext(html.match(/function toggleCocWeaponDetail\([^]*?\n\}/)[0], context);
const detail = { hidden: true, querySelector: () => ({ value: '' }) };
const toggle = { closest: () => ({ nextElementSibling: detail }), setAttribute(key, value) { this[key] = value; } };
context.toggleCocWeaponDetail(toggle);
assert.equal(detail.hidden, false);
assert.equal(toggle['aria-expanded'], 'true');
context.toggleCocWeaponDetail(toggle);
assert.equal(detail.hidden, true);
let options, saved;
context.tbShowCtxMenu = (_x, _y, items) => { options = items; };
context.document = { querySelector: () => ({ style: {}, setAttribute() {}, querySelectorAll: () => [] }) };
context.saveSheetRepeatCell = (...args) => { saved = args; };
vm.runInContext(html.match(/function openCocWeaponDbMenu\([^]*?\n\}/)[0], context);
const button = { getBoundingClientRect: () => ({ left: 0, bottom: 20, width: 64 }), focus() {} };
context.openCocWeaponDbMenu({ stopPropagation() {}, currentTarget: button }, 'c', 's', 0);
options[2].action();
assert.equal(button.textContent, '+½DB');
assert.deepEqual(saved, ['c', 's', 'weapons', 0, 'db', '+½db']);
